web:
  restart: always
  build: ../his
  expose:
    - "8000"
  # links:
  #   - postgres
  #   - redis
  volumes:
    - /appmedia:/appmedia
    - /appstatic
  # env_file: .env
  command: /usr/local/bin/gunicorn his.wsgi:application -w 2 -b :8000

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - web
  links:
    - web

# postgres:
#   restart: always
#   image: postgres:latest
#   volumes_from:
#     - data
#   ports:
#     - "5432:5432"

# redis:
#   restart: always
#   image: redis:latest
#   ports:
#     - "6379:6379"

data:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: /bin/true
